DROP TABLE IF EXISTS author CASCADE;
CREATE TABLE author(
   ID  BIGSERIAL PRIMARY KEY,
   FIRST_NAME VARCHAR (80)  NOT NULL,
   LAST_NAME  VARCHAR (80)  NOT NULL
);

DROP TABLE IF EXISTS genre CASCADE;
CREATE TABLE genre(
   ID BIGSERIAL PRIMARY KEY,
   NAME VARCHAR (80)  NOT NULL
);

DROP TABLE IF EXISTS book CASCADE;
CREATE TABLE book(
   ID  BIGSERIAL  PRIMARY KEY,
   NAME VARCHAR (80) NOT NULL,
   AUTHOR_ID  BIGINT
      REFERENCES  author(ID) MATCH SIMPLE
         ON DELETE SET NULL ,
   GENRE_ID BIGINT REFERENCES  genre(ID) MATCH SIMPLE
         ON DELETE SET NULL
);

DROP TABLE IF EXISTS book_comment;
CREATE TABLE book_comment(
   ID  BIGSERIAL  PRIMARY KEY,
   COMMENT VARCHAR (255) NOT NULL,
   BOOK_ID  BIGINT
      REFERENCES  book(ID)
         ON DELETE CASCADE
);