DROP TABLE IF EXISTS author;
CREATE TABLE author(
   AUTHOR_ID  SERIAL PRIMARY KEY,
   FIRST_NAME VARCHAR (80)  NOT NULL,
   LAST_NAME  VARCHAR (80)  NOT NULL
);

DROP TABLE IF EXISTS genre;
CREATE TABLE genre(
   GENRE_ID SERIAL PRIMARY KEY,
   NAME VARCHAR (80)  NOT NULL
);

DROP TABLE IF EXISTS book;
CREATE TABLE book(
   BOOK_ID  SERIAL  PRIMARY KEY,
   AUTHOR_ID  INT REFERENCES  author(AUTHOR_ID),
   GENRE_ID INT REFERENCES  genre(GENRE_ID)
);