DROP TABLE IF EXISTS author;
CREATE TABLE author(
   ID  BIGSERIAL PRIMARY KEY,
   FIRST_NAME VARCHAR (80)  NOT NULL,
   LAST_NAME  VARCHAR (80)  NOT NULL
);

DROP TABLE IF EXISTS genre;
CREATE TABLE genre(
   ID BIGSERIAL PRIMARY KEY,
   NAME VARCHAR (80)  NOT NULL
);

DROP TABLE IF EXISTS book;
CREATE TABLE book(
   ID  BIGSERIAL  PRIMARY KEY,
   NAME VARCHAR (80) NOT NULL,
   AUTHOR_ID  BIGINT
      REFERENCES  author(ID),
   GENRE_ID BIGINT
      REFERENCES  genre(ID)
);

DROP TABLE IF EXISTS book_comment;
CREATE TABLE book_comment(
   ID  BIGSERIAL  PRIMARY KEY,
   COMMENT VARCHAR (255) NOT NULL,
   BOOK_ID  BIGINT
      REFERENCES  book(ID)
         ON DELETE CASCADE
);