DROP TABLE IF EXISTS author;
CREATE TABLE author(
   ID  BIGSERIAL PRIMARY KEY,
   FIRST_NAME VARCHAR (80)  NOT NULL,
   LAST_NAME  VARCHAR (80)  NOT NULL
);

DROP TABLE IF EXISTS genre;
CREATE TABLE genre(
   ID BIGSERIAL PRIMARY KEY,
   NAME VARCHAR (80)  NOT NULL
);

DROP TABLE IF EXISTS book;
CREATE TABLE book(
   ID  BIGSERIAL  PRIMARY KEY,
   NAME VARCHAR (80) NOT NULL,
   AUTHOR_ID  BIGINT
      REFERENCES  author(ID),
   GENRE_ID BIGINT
      REFERENCES  genre(ID)
);

DROP TABLE IF EXISTS book_comment;
CREATE TABLE book_comment(
   ID  BIGSERIAL  PRIMARY KEY,
   COMMENT VARCHAR (255) NOT NULL,
   BOOK_ID  BIGINT
      REFERENCES  book(ID)
         ON DELETE CASCADE
);

DROP TABLE IF EXISTS APP_USER;
CREATE TABLE APP_USER
(
   ID           BIGSERIAL  NOT NULL PRIMARY KEY,
   USER_NAME         VARCHAR(36)  NOT NULL UNIQUE ,
   ENCRYPTED_PASSWORD VARCHAR(128)  NOT NULL,
   ENABLED           INT  NOT NULL

) ;

DROP TABLE IF EXISTS APP_ROLE;
create table APP_ROLE
(
   ROLE_ID   BIGSERIAL NOT NULL PRIMARY KEY,
   ROLE_NAME VARCHAR(30) NOT NULL UNIQUE
) ;

DROP TABLE IF EXISTS USER_ROLE;
create table USER_ROLE
(
   ID      BIGSERIAL NOT NULL PRIMARY KEY,
   USER_ID BIGSERIAL NOT NULL REFERENCES APP_USER (ID),
   ROLE_ID BIGSERIAL NOT NULL REFERENCES APP_ROLE (ROLE_ID)
);

